"""MuseForge FastAPI backend."""

import asyncio
import json
import logging
import os
import re
import time
from collections import defaultdict
from contextlib import asynccontextmanager
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

import httpx
from dotenv import load_dotenv
from fastapi import BackgroundTasks, Depends, FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse, RedirectResponse, StreamingResponse
from pydantic import BaseModel, Field

from auth import (
    SUPABASE_SERVICE_KEY,
    SUPABASE_URL,
    AuthUser,
    get_current_admin,
    get_current_user,
    get_optional_user,
)
from interfaces.camera import DIRECTOR_STYLES
from tools.muapi_voice_generator import is_dialogue_enabled
from jobs import (
    JOBS_DIR,
    JobStatus,
    job_store,
    run_continue_from_script_job,
    run_generation_job,
)

load_dotenv()

ALLOWED_ORIGINS = os.environ.get(
    "ALLOWED_ORIGINS",
    os.environ.get(
        "CORS_ORIGINS",
        "http://localhost:3000,http://127.0.0.1:3000,"
        "https://museforge.studio,https://www.museforge.studio",
    ),
).split(",")

# Vercel gives every preview deployment its own random subdomain
# (e.g. https://muse-forge-i3ah-1vo7vxdxh-alt-051.vercel.app), which can
# never be fully enumerated in a static ALLOWED_ORIGINS list. Also cover
# the production custom domain (with or without "www.") here too, as a
# defense-in-depth fallback in case ALLOWED_ORIGINS ever gets overridden
# on the hosting platform without the domain included. Match both via
# regex so neither Vercel previews nor the custom domain break silently.
# Override via ALLOWED_ORIGIN_REGEX if you need something stricter/different.
ALLOWED_ORIGIN_REGEX = os.environ.get(
    "ALLOWED_ORIGIN_REGEX",
    r"https://(.*\.vercel\.app|(www\.)?museforge\.studio)",
)

DEMO_FLAG = os.environ.get("MUSEFORGE_DEMO", "").lower() in ("1", "true", "yes")
SECONDS_PER_SCENE = float(os.environ.get("MUSEFORGE_SECONDS_PER_SCENE", "180"))


def _is_demo() -> bool:
    return DEMO_FLAG or not bool(os.environ.get("MUAPI_KEY"))


# ── Rate limiter (sliding-window, no external dependencies) ───────────────────

class _SlidingWindowRateLimiter:
    """Per-key sliding-window rate limiter using monotonic clock.

    Keeps a list of hit timestamps per key and trims them on every check.
    The memory footprint is bounded by limit * number_of_unique_keys.
    """

    def __init__(self, limit: int = 5, window: float = 60.0):
        self._limit = limit
        self._window = window
        self._hits: dict[str, list[float]] = defaultdict(list)

    def allow(self, key: str) -> bool:
        now = time.monotonic()
        cutoff = now - self._window
        hits = [t for t in self._hits[key] if t > cutoff]
        if len(hits) >= self._limit:
            self._hits[key] = hits
            return False
        hits.append(now)
        self._hits[key] = hits
        return True


# 5 generate requests per 60 s per authenticated user / IP
_rate_limiter = _SlidingWindowRateLimiter(limit=5, window=60.0)


@asynccontextmanager
async def lifespan(app: FastAPI):
    jobs_dir = os.environ.get("MUSEFORGE_JOBS_DIR", "/tmp/museforge_jobs")
    os.makedirs(jobs_dir, exist_ok=True)
    # Independent background tasks (disk orphans + stale DB job rows)
    from jobs import orphan_cleanup_loop, stale_job_reaper_loop

    cleanup_task = asyncio.create_task(orphan_cleanup_loop())
    reaper_task = asyncio.create_task(stale_job_reaper_loop())
    try:
        yield
    finally:
        cleanup_task.cancel()
        reaper_task.cancel()
        for task in (cleanup_task, reaper_task):
            try:
                await task
            except asyncio.CancelledError:
                pass


app = FastAPI(title="MuseForge API", version="2.3.0", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_origin_regex=ALLOWED_ORIGIN_REGEX,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def _cors_header_for(request: Request) -> dict:
    """Build the Access-Control-Allow-Origin header for a manual error
    response, matching the same allow_origins/allow_origin_regex rules as
    CORSMiddleware above.

    NOTE ON WHY THIS EXISTS: Starlette's CORSMiddleware does NOT add CORS
    headers to 500 responses caused by an unhandled exception -- those are
    generated by ServerErrorMiddleware, which sits OUTSIDE CORSMiddleware
    in the default stack. The practical effect: any unhandled backend
    exception shows up in the browser as a generic, misleading "blocked by
    CORS policy" error, hiding the real 500 and its message. This handler
    ensures every error response -- not just successful ones -- carries a
    correct CORS header, and surfaces the real error message to the client
    instead of a CORS red herring.
    """
    origin = request.headers.get("origin", "")
    if not origin:
        return {}
    if origin in ALLOWED_ORIGINS:
        return {"Access-Control-Allow-Origin": origin, "Vary": "Origin"}
    if ALLOWED_ORIGIN_REGEX and re.match(ALLOWED_ORIGIN_REGEX, origin):
        return {"Access-Control-Allow-Origin": origin, "Vary": "Origin"}
    return {}


@app.exception_handler(Exception)
async def _unhandled_exception_handler(request: Request, exc: Exception):
    logger.exception(f"Unhandled error on {request.method} {request.url.path}: {exc}")
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal server error. Please try again."},
        headers=_cors_header_for(request),
    )


@app.middleware("http")
async def security_headers(request: Request, call_next):
    response = await call_next(request)
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
    response.headers["Strict-Transport-Security"] = "max-age=63072000; includeSubDomains"
    return response


# ── Request / Response models ─────────────────────────────────────────────────

class LibraryCharacterIn(BaseModel):
    name: str = Field(..., min_length=1, max_length=120)
    static_features: str = Field(..., min_length=1, max_length=2000)
    portrait_url: str = Field(..., min_length=1, max_length=2000)


class GenerateRequest(BaseModel):
    idea: str = Field(..., min_length=3, max_length=2000)
    style: str = "Cinematic"
    director_style: str = "cinematic_balanced"
    aspect_ratio: str = "16:9"
    num_scenes: int = Field(default=3, ge=2, le=5)
    user_requirement: str = ""
    character_image: Optional[str] = None
    character_name: str = ""
    # Pro-only: reuse locked portraits from the character library.
    library_characters: List[LibraryCharacterIn] = Field(default_factory=list)
    # Optional instrumental background music. Only honoured for Creator/Pro
    # plans (checked server-side against the caller's actual plan) — silently
    # ignored for free/anonymous requests rather than erroring.
    music_enabled: bool = False
    # Optional character dialogue. Pro-only and additionally protected by
    # MUSEFORGE_DIALOGUE_ENABLED so the infrastructure can be disabled globally.
    dialogue_enabled: bool = False
    # When True: write script only, pause for user edit/approve. No credits
    # charged until POST /api/jobs/{id}/approve-script.
    require_script_approval: bool = False


class CharacterCreateRequest(BaseModel):
    name: str = Field(..., min_length=1, max_length=120)
    static_features: str = Field(..., min_length=1, max_length=2000)
    portrait_url: str = Field(..., min_length=1, max_length=2000)


class GenerateResponse(BaseModel):
    job_id: str
    demo: bool


class ExportRequest(BaseModel):
    aspect_ratio: str = Field(..., pattern=r"^(9:16|1:1)$")


class ExportResponse(BaseModel):
    video_url: str
    aspect_ratio: str
    # Naive center-crop disclaimer — not smart subject-aware reframing.
    note: str = "Simple center crop from the original video (edges may be lost)."


class ApproveScriptRequest(BaseModel):
    script: dict


class EstimateRequest(BaseModel):
    num_scenes: int = Field(default=3, ge=2, le=5)
    music_enabled: bool = False
    dialogue_enabled: bool = False
    # Client-supplied plan for the credit breakdown preview. The generate
    # path always re-checks the caller's real plan server-side; spoofing
    # here only changes the displayed estimate, not billing.
    plan: str = "free"


# ── Plan helpers ──────────────────────────────────────────────────────────────

# Real, currently-enforced plan differentiators. Keep in sync with
# supabase_migration.sql's public.plan_limits view and client/lib/i18n
# plan_*_features strings. Do NOT add a plan feature here (or to the pricing
# copy) unless there's an actual enforcement mechanism behind it.
PLAN_MAX_SCENES = {"free": 3, "creator": 3, "pro": 5}
MUSIC_EXTRA_CREDIT_COST = 1  # flat surcharge on top of scene credits, Creator/Pro only
DIALOGUE_EXTRA_CREDIT_COST = 1  # per scene, Pro only


def build_credit_breakdown(
    num_scenes: int,
    *,
    music_enabled: bool = False,
    dialogue_enabled: bool = False,
    plan: str = "free",
) -> dict:
    """Line-item credit cost matching what /api/generate will charge.

    Only includes surcharges that would actually apply (flag on + plan
    eligible + dialogue feature flag). Closed options are omitted entirely.
    """
    plan = (plan or "free").lower()
    music_on = bool(music_enabled) and plan in ("creator", "pro")
    dialogue_on = (
        bool(dialogue_enabled) and plan == "pro" and is_dialogue_enabled()
    )

    breakdown = [
        {
            "label": f"Temel üretim ({num_scenes} sahne)",
            "credits": num_scenes,
        }
    ]
    total = num_scenes

    if music_on:
        breakdown.append({"label": "Müzik", "credits": MUSIC_EXTRA_CREDIT_COST})
        total += MUSIC_EXTRA_CREDIT_COST

    if dialogue_on:
        dialogue_credits = num_scenes * DIALOGUE_EXTRA_CREDIT_COST
        breakdown.append({"label": "Diyalog", "credits": dialogue_credits})
        total += dialogue_credits

    return {"total_credits": total, "breakdown": breakdown}


# ── Public endpoints ──────────────────────────────────────────────────────────

@app.get("/api/health")
async def health():
    return {
        "status": "ok",
        "service": "museforge-api",
        "version": "2.3.0",
        "demo_mode": _is_demo(),
        "muapi_configured": bool(os.environ.get("MUAPI_KEY")),
        "claude_configured": bool(os.environ.get("ANTHROPIC_API_KEY")),
        # True if the screenwriter/storyboard agents have ANY working LLM
        # path (MuAPI's Claude route tried first, direct Anthropic as
        # fallback) -- distinct from claude_configured, which only reflects
        # the direct-Anthropic fallback and doesn't tell you if MuAPI alone
        # is already covering it.
        "creative_llm_available": bool(
            os.environ.get("MUAPI_KEY") or os.environ.get("ANTHROPIC_API_KEY")
        ),
        "auth_configured": bool(SUPABASE_URL),
    }


@app.get("/api/stats")
async def public_stats():
    """Return public job counts for the live counter on the homepage."""
    total = 0
    monthly = 0
    if SUPABASE_URL and SUPABASE_SERVICE_KEY:
        try:
            async with httpx.AsyncClient(timeout=5.0) as client:
                now = time.time()
                import datetime
                first_of_month = datetime.datetime.utcnow().replace(
                    day=1, hour=0, minute=0, second=0, microsecond=0
                ).isoformat() + "Z"
                headers = {
                    "apikey": SUPABASE_SERVICE_KEY,
                    "Authorization": f"Bearer {SUPABASE_SERVICE_KEY}",
                    "Prefer": "count=exact",
                    "Range": "0-0",
                }
                r_total = await client.get(
                    f"{SUPABASE_URL}/rest/v1/jobs?select=id&status=eq.completed",
                    headers=headers,
                )
                r_monthly = await client.get(
                    f"{SUPABASE_URL}/rest/v1/jobs?select=id&status=eq.completed&created_at=gte.{first_of_month}",
                    headers=headers,
                )
                if r_total.status_code == 206:
                    cr = r_total.headers.get("Content-Range", "")
                    total = int(cr.split("/")[-1]) if "/" in cr else 0
                if r_monthly.status_code == 206:
                    cr = r_monthly.headers.get("Content-Range", "")
                    monthly = int(cr.split("/")[-1]) if "/" in cr else 0
        except Exception:
            pass
    # Fall back to in-memory count when Supabase not configured
    if total == 0 and monthly == 0:
        jobs = list(job_store._jobs.values())
        total = sum(1 for j in jobs if j.status == JobStatus.COMPLETED)
        monthly = total
    return {"total_completed": total, "monthly_completed": monthly}


@app.get("/api/director-styles")
async def director_styles():
    return {
        name: {
            "label": style.label,
            "default_lens": style.default_lens,
            "pacing": style.pacing,
            "color_grade": style.color_grade,
        }
        for name, style in DIRECTOR_STYLES.items()
    }


@app.post("/api/estimate")
async def estimate(req: EstimateRequest):
    demo = _is_demo()
    seconds = 5 if demo else int(req.num_scenes * SECONDS_PER_SCENE)
    credits = build_credit_breakdown(
        req.num_scenes,
        music_enabled=req.music_enabled,
        dialogue_enabled=req.dialogue_enabled,
        plan=req.plan,
    )
    return {
        "num_scenes": req.num_scenes,
        "estimated_seconds": seconds,
        "estimated_label": f"~{seconds}s" if seconds < 60 else f"~{round(seconds / 60, 1)} min",
        "asset_count": {
            "portraits": 1,
            "frames": req.num_scenes,
            "clips": req.num_scenes,
        },
        "demo": demo,
        "total_credits": credits["total_credits"],
        "breakdown": credits["breakdown"],
    }


async def _get_user_plan(user_id: str) -> str:
    """Return the user's subscription plan ('free', 'creator', 'pro').

    Returns 'pro' (unrestricted) when Supabase isn't configured, matching
    _get_user_credits' dev-mode fallback. Returns 'free' on lookup failure —
    the safest default since it's the most restrictive plan.
    """
    if not SUPABASE_URL or not SUPABASE_SERVICE_KEY:
        return "pro"
    try:
        async with httpx.AsyncClient(timeout=6.0) as client:
            resp = await client.get(
                f"{SUPABASE_URL}/rest/v1/profiles",
                params={"id": f"eq.{user_id}", "select": "plan", "limit": "1"},
                headers={"apikey": SUPABASE_SERVICE_KEY, "Authorization": f"Bearer {SUPABASE_SERVICE_KEY}"},
            )
            data = resp.json()
            if isinstance(data, list) and data:
                return data[0].get("plan") or "free"
    except Exception as exc:
        logger.error("_get_user_plan failed for user %s: %s", user_id, exc)
    return "free"


# ── Credit helpers ────────────────────────────────────────────────────────────

async def _get_user_credits(user_id: str) -> int:
    """Return the current credit balance for a user. Returns -1 on Supabase error."""
    if not SUPABASE_URL or not SUPABASE_SERVICE_KEY:
        return 9999  # unlimited in dev
    try:
        async with httpx.AsyncClient(timeout=6.0) as client:
            resp = await client.get(
                f"{SUPABASE_URL}/rest/v1/profiles",
                params={"id": f"eq.{user_id}", "select": "credits", "limit": "1"},
                headers={"apikey": SUPABASE_SERVICE_KEY, "Authorization": f"Bearer {SUPABASE_SERVICE_KEY}"},
            )
            data = resp.json()
            if isinstance(data, list) and data:
                return data[0].get("credits", 0)
    except Exception:
        pass
    return -1


async def _deduct_credits(user_id: str, amount: int, reason: str = "video_generation", job_id: str = "") -> bool:
    """Atomically deduct `amount` credits via Supabase RPC. Returns False if insufficient.

    Uses a PostgreSQL function that performs a single conditional UPDATE, preventing
    race conditions from the old read-then-write pattern.
    """
    if not SUPABASE_URL or not SUPABASE_SERVICE_KEY:
        return True
    try:
        async with httpx.AsyncClient(timeout=8.0) as client:
            sb_headers = {
                "apikey": SUPABASE_SERVICE_KEY,
                "Authorization": f"Bearer {SUPABASE_SERVICE_KEY}",
                "Content-Type": "application/json",
            }
            # Atomic deduction via RPC — returns new balance, or -1 if insufficient
            rpc_resp = await client.post(
                f"{SUPABASE_URL}/rest/v1/rpc/deduct_credits",
                json={"p_user_id": user_id, "p_amount": amount},
                headers=sb_headers,
            )
            new_balance = rpc_resp.json()
            if new_balance == -1:
                return False  # insufficient credits
            # Fire-and-forget ledger entry
            ledger_payload = {"user_id": user_id, "amount": -amount, "reason": reason}
            if job_id:
                ledger_payload["job_id"] = job_id
            await client.post(
                f"{SUPABASE_URL}/rest/v1/credit_ledger",
                json=ledger_payload,
                headers={**sb_headers, "Prefer": "return=minimal"},
            )
        return True
    except Exception as exc:
        logger.error("_deduct_credits failed for user %s: %s", user_id, exc)
        return True  # fail-open: don't block generation on Supabase outages


# ── Generation (rate-limited; auth optional for demo mode) ───────────────────

@app.post("/api/generate", response_model=GenerateResponse)
async def generate(
    req: GenerateRequest,
    request: Request,
    background_tasks: BackgroundTasks,
    current_user: Optional[AuthUser] = Depends(get_optional_user),
):
    if req.director_style not in DIRECTOR_STYLES:
        raise HTTPException(status_code=400, detail=f"Unknown director style: {req.director_style}")

    # Rate-limit key: authenticated user_id preferred; fallback to client IP
    rl_key = (
        current_user.user_id
        if current_user
        else (request.client.host if request.client else "anon")
    )
    if not _rate_limiter.allow(rl_key):
        raise HTTPException(
            status_code=429,
            detail="Çok fazla istek. Lütfen 1 dakika bekleyin ve tekrar deneyin.",
            headers={"Retry-After": "60"},
        )

    demo = _is_demo()
    api_key = os.environ.get("MUAPI_KEY", "")

    # Block unauthenticated users outside demo mode
    if not demo and current_user is None:
        raise HTTPException(
            status_code=401,
            detail="Authentication required. Please sign in to generate videos.",
        )

    # Plan lookup, scene-limit enforcement, credit check — only for
    # authenticated non-demo requests. Demo/anonymous requests fall back to
    # the free-tier defaults (no music, watermark applies) and only the
    # Pydantic-level bounds on num_scenes.
    # When require_script_approval is True, credits are NOT charged here —
    # they are charged at approve-script time so the user can abandon a
    # bad script for free.
    plan = "free"
    music_enabled = False
    dialogue_enabled = False
    if current_user and not demo:
        plan = await _get_user_plan(current_user.user_id)

        max_scenes = PLAN_MAX_SCENES.get(plan, PLAN_MAX_SCENES["free"])
        if req.num_scenes > max_scenes:
            raise HTTPException(
                status_code=400,
                detail=f"Your plan allows up to {max_scenes} scenes. Upgrade to generate longer videos.",
            )

        # Optional background music — Creator/Pro only. Free/anonymous requests
        # that send music_enabled=True are silently ignored, not rejected.
        music_enabled = bool(req.music_enabled) and plan in ("creator", "pro")
        # Dialogue is intentionally Pro-only. Both the deployment-level feature
        # flag and the per-request opt-in must be enabled.
        dialogue_enabled = (
            bool(req.dialogue_enabled)
            and plan == "pro"
            and is_dialogue_enabled()
        )

        if not req.require_script_approval:
            credit_cost = build_credit_breakdown(
                req.num_scenes,
                music_enabled=music_enabled,
                dialogue_enabled=dialogue_enabled,
                plan=plan,
            )["total_credits"]
            ok = await _deduct_credits(current_user.user_id, credit_cost, "video_generation")
            if not ok:
                raise HTTPException(
                    status_code=402,
                    detail=f"Insufficient credits. You need {credit_cost} credits for this generation. Please top up your balance.",
                )

    # Pro-only library characters (name + static_features + portrait_url).
    # Free/Creator payloads that include this field are silently dropped.
    library_characters: List[dict] = []
    if current_user and not demo and plan == "pro" and req.library_characters:
        library_characters = [
            {
                "name": c.name.strip(),
                "static_features": c.static_features.strip(),
                "portrait_url": c.portrait_url.strip(),
            }
            for c in req.library_characters
            if c.name.strip() and c.static_features.strip() and c.portrait_url.strip()
        ]

    job = await job_store.create(
        idea=req.idea,
        style=req.style,
        director_style=req.director_style,
        aspect_ratio=req.aspect_ratio,
        num_scenes=req.num_scenes,
        user_requirement=req.user_requirement,
        demo=demo,
        user_id=current_user.user_id if current_user else None,
        user_email=current_user.email if current_user else None,
        character_image=req.character_image,
        character_name=req.character_name,
        music_enabled=music_enabled,
        dialogue_enabled=dialogue_enabled,
        plan=plan,
        require_script_approval=bool(req.require_script_approval),
        library_characters=library_characters,
    )

    background_tasks.add_task(run_generation_job, job, api_key)
    return GenerateResponse(job_id=job.id, demo=demo)


# ── Job endpoints (auth optional for public demo jobs) ───────────────────────

@app.get("/api/jobs/{job_id}")
async def get_job(
    job_id: str,
    current_user: Optional[AuthUser] = Depends(get_optional_user),
):
    job = job_store.get(job_id)
    if job:
        # Auth guard for in-memory jobs
        if current_user and job.user_id and job.user_id != current_user.user_id:
            if not current_user.is_admin:
                raise HTTPException(status_code=403, detail="Access denied")
        return job.to_dict()

    # Cache miss (post-restart): try Supabase
    data = await job_store.get_or_fetch_dict(job_id)
    if not data:
        raise HTTPException(status_code=404, detail="Job not found")

    if current_user and data.get("user_id") and data["user_id"] != current_user.user_id:
        if not current_user.is_admin:
            raise HTTPException(status_code=403, detail="Access denied")
    return data


@app.get("/api/jobs/{job_id}/video")
async def get_job_video(job_id: str, format: Optional[str] = None):
    job = job_store.get(job_id)

    if job:
        result = job.result
    else:
        # Post-restart fallback
        data = await job_store.get_or_fetch_dict(job_id)
        result = data.get("result") if data else None

    if not result:
        raise HTTPException(status_code=404, detail="Video not ready")

    # Alternate center-crop exports: ?format=9x16 or ?format=1x1
    if format:
        ratio_key = format.replace("x", ":")
        exp = (result.get("exports") or {}).get(ratio_key) or (result.get("exports") or {}).get(format)
        if isinstance(exp, dict):
            ep = exp.get("video_path")
            if ep and os.path.exists(ep):
                return FileResponse(
                    ep, media_type="video/mp4", filename=f"museforge_{job_id}_{format}.mp4"
                )
            eu = exp.get("video_url")
            if eu and str(eu).startswith(("http://", "https://")):
                return RedirectResponse(eu)

    path = result.get("video_path")
    if path and os.path.exists(path):
        return FileResponse(path, media_type="video/mp4", filename=f"museforge_{job_id}.mp4")

    url = result.get("video_url")
    if url:
        return RedirectResponse(url)

    raise HTTPException(status_code=404, detail="Video not available")


async def _resolve_job_source_video(job) -> str:
    """Return a local filesystem path to the job's master video for export.

    Prefers an existing local ``video_path``; otherwise downloads from
    ``video_url`` into the job working dir. Raises HTTPException on failure.
    """
    from pipelines.script2video import download_video

    result = job.result or {}
    path = result.get("video_path")
    if path and os.path.isfile(path):
        return path

    working_dir = os.path.join(JOBS_DIR, job.id)
    os.makedirs(working_dir, exist_ok=True)

    # Common local filenames left behind when Storage upload was skipped.
    for name in ("drama_final.mp4", "drama_with_music.mp4", "drama_concatenated.mp4"):
        candidate = os.path.join(working_dir, name)
        if os.path.isfile(candidate):
            return candidate

    url = result.get("video_url")
    if url and isinstance(url, str) and url.startswith(("http://", "https://")):
        local = os.path.join(working_dir, "export_source.mp4")
        if not os.path.isfile(local):
            await download_video(url, local)
        if os.path.isfile(local):
            return local

    raise HTTPException(
        status_code=404,
        detail="Source video not available for export",
    )


@app.post("/api/jobs/{job_id}/export", response_model=ExportResponse)
async def export_job_format(
    job_id: str,
    req: ExportRequest,
    current_user: Optional[AuthUser] = Depends(get_optional_user),
):
    """Center-crop the finished master into 9:16 or 1:1. No MuAPI, no credits.

    This is a *simple center crop* — not smart subject-aware reframing.
    Edge content from the original frame may be lost.
    """
    from pipelines.idea2video import export_alternate_format
    from tools.supabase_storage import upload_video

    job = job_store.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")

    if current_user and job.user_id and job.user_id != current_user.user_id:
        if not current_user.is_admin:
            raise HTTPException(status_code=403, detail="Access denied")

    if job.status != JobStatus.COMPLETED or not job.result:
        raise HTTPException(status_code=400, detail="Job is not completed")

    # Cache hit: already exported this ratio.
    exports = (job.result or {}).setdefault("exports", {})
    cached = exports.get(req.aspect_ratio)
    if isinstance(cached, dict) and cached.get("video_url"):
        return ExportResponse(
            video_url=cached["video_url"],
            aspect_ratio=req.aspect_ratio,
        )

    source = await _resolve_job_source_video(job)
    working_dir = os.path.join(JOBS_DIR, job.id)
    os.makedirs(working_dir, exist_ok=True)
    safe_ratio = req.aspect_ratio.replace(":", "x")
    output_path = os.path.join(working_dir, f"export_{safe_ratio}.mp4")

    try:
        await export_alternate_format(source, output_path, req.aspect_ratio)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    except Exception as exc:
        logger.exception("export_alternate_format failed for job %s", job_id)
        raise HTTPException(status_code=500, detail=f"Export failed: {exc}") from exc

    video_url = f"/api/jobs/{job_id}/video?format={safe_ratio}"
    # Best-effort Storage upload under a distinct object key.
    if not job.demo:
        try:
            # upload_video uses {job_id}.mp4 — pass a synthetic id for variants.
            stored = await upload_video(output_path, f"{job_id}_{safe_ratio}")
            if stored and stored.startswith("http"):
                video_url = stored
        except Exception as exc:
            logger.warning("Export upload failed (serving local): %s", exc)

    exports[req.aspect_ratio] = {
        "video_path": output_path,
        "video_url": video_url,
    }
    job.result["exports"] = exports
    await job_store.persist(job)

    return ExportResponse(video_url=video_url, aspect_ratio=req.aspect_ratio)


@app.post("/api/jobs/{job_id}/approve-script")
async def approve_script(
    job_id: str,
    req: ApproveScriptRequest,
    background_tasks: BackgroundTasks,
    current_user: Optional[AuthUser] = Depends(get_optional_user),
):
    """Charge credits (if needed) and continue production from an edited script."""
    from interfaces.character import DramaScript

    job = job_store.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")

    if current_user and job.user_id and job.user_id != current_user.user_id:
        if not current_user.is_admin:
            raise HTTPException(status_code=403, detail="Access denied")

    if job.status != JobStatus.AWAITING_SCRIPT_APPROVAL:
        raise HTTPException(
            status_code=400,
            detail=f"Job is not awaiting script approval (status={job.status.value})",
        )

    try:
        script = DramaScript(**(req.script or {}))
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Invalid script: {exc}") from exc

    demo = job.demo or _is_demo()
    api_key = os.environ.get("MUAPI_KEY", "")

    # Charge credits here — script phase was free.
    if current_user and not demo and job.user_id:
        credit_cost = (
            job.num_scenes
            + (MUSIC_EXTRA_CREDIT_COST if job.music_enabled else 0)
            + (
                job.num_scenes * DIALOGUE_EXTRA_CREDIT_COST
                if job.dialogue_enabled
                else 0
            )
        )
        ok = await _deduct_credits(
            job.user_id, credit_cost, "video_generation", job_id=job.id
        )
        if not ok:
            raise HTTPException(
                status_code=402,
                detail=f"Insufficient credits. You need {credit_cost} credits for this generation.",
            )

    script_data = script.model_dump()
    job.result = {**(job.result or {}), "script": script_data}
    job.status = JobStatus.RUNNING
    await job_store.persist(job)
    await job_store.emit(job, "screenwriting", "Script approved — starting production", 12)

    background_tasks.add_task(run_continue_from_script_job, job, api_key, script_data)
    return {"job_id": job.id, "status": job.status.value}


@app.get("/api/jobs/{job_id}/stream")
async def stream_job(job_id: str):
    job = job_store.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")

    async def event_generator():
        async for event in job_store.subscribe(job_id):
            yield f"data: {json.dumps(event.to_dict())}\n\n"
        final = job_store.get(job_id)
        if final:
            yield f"data: {json.dumps({'stage': 'done', 'status': final.status.value, 'progress': 100})}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "Connection": "keep-alive", "X-Accel-Buffering": "no"},
    )


@app.post("/api/jobs/{job_id}/cancel")
async def cancel_job(
    job_id: str,
    current_user: Optional[AuthUser] = Depends(get_optional_user),
):
    job = job_store.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    if job.status in (JobStatus.COMPLETED, JobStatus.FAILED, JobStatus.CANCELLED):
        raise HTTPException(status_code=400, detail="Job already finished")
    if current_user and job.user_id and job.user_id != current_user.user_id:
        if not current_user.is_admin:
            raise HTTPException(status_code=403, detail="Access denied")
    job.status = JobStatus.CANCELLED
    await job_store.persist(job)
    return {"status": "cancelled"}


# ── Character library (Pro) ───────────────────────────────────────────────────

# In-memory fallback when Supabase isn't configured (local/demo/tests).
_character_library_mem: Dict[str, List[Dict[str, Any]]] = defaultdict(list)


def _sb_headers() -> dict:
    return {
        "apikey": SUPABASE_SERVICE_KEY,
        "Authorization": f"Bearer {SUPABASE_SERVICE_KEY}",
        "Content-Type": "application/json",
        "Prefer": "return=representation",
    }


async def _library_list(user_id: str) -> List[Dict[str, Any]]:
    if not SUPABASE_URL or not SUPABASE_SERVICE_KEY:
        return list(_character_library_mem.get(user_id, []))
    try:
        async with httpx.AsyncClient(timeout=8.0) as client:
            resp = await client.get(
                f"{SUPABASE_URL}/rest/v1/character_library",
                params={
                    "user_id": f"eq.{user_id}",
                    "select": "id,name,static_features,portrait_url,created_at",
                    "order": "created_at.desc",
                },
                headers=_sb_headers(),
            )
            if resp.status_code >= 400:
                logger.error("character_library list failed: %s", resp.text[:300])
                return []
            data = resp.json()
            return data if isinstance(data, list) else []
    except Exception as exc:
        logger.error("character_library list error: %s", exc)
        return []


async def _library_insert(user_id: str, payload: dict) -> Dict[str, Any]:
    import uuid as _uuid
    from datetime import datetime, timezone

    if not SUPABASE_URL or not SUPABASE_SERVICE_KEY:
        row = {
            "id": str(_uuid.uuid4()),
            "user_id": user_id,
            "name": payload["name"],
            "static_features": payload["static_features"],
            "portrait_url": payload["portrait_url"],
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
        _character_library_mem[user_id].insert(0, row)
        return row
    try:
        async with httpx.AsyncClient(timeout=8.0) as client:
            resp = await client.post(
                f"{SUPABASE_URL}/rest/v1/character_library",
                headers=_sb_headers(),
                json={
                    "user_id": user_id,
                    "name": payload["name"],
                    "static_features": payload["static_features"],
                    "portrait_url": payload["portrait_url"],
                },
            )
            if resp.status_code >= 400:
                logger.error("character_library insert failed: %s", resp.text[:300])
                raise HTTPException(status_code=502, detail="Failed to save character")
            data = resp.json()
            if isinstance(data, list) and data:
                return data[0]
            if isinstance(data, dict):
                return data
            raise HTTPException(status_code=502, detail="Failed to save character")
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("character_library insert error: %s", exc)
        raise HTTPException(status_code=502, detail="Failed to save character") from exc


async def _library_delete(user_id: str, character_id: str) -> bool:
    if not SUPABASE_URL or not SUPABASE_SERVICE_KEY:
        before = len(_character_library_mem.get(user_id, []))
        _character_library_mem[user_id] = [
            c for c in _character_library_mem.get(user_id, []) if c.get("id") != character_id
        ]
        return len(_character_library_mem.get(user_id, [])) < before
    try:
        async with httpx.AsyncClient(timeout=8.0) as client:
            resp = await client.delete(
                f"{SUPABASE_URL}/rest/v1/character_library",
                params={"id": f"eq.{character_id}", "user_id": f"eq.{user_id}"},
                headers=_sb_headers(),
            )
            return resp.status_code < 400
    except Exception as exc:
        logger.error("character_library delete error: %s", exc)
        return False


@app.post("/api/characters")
async def create_character(
    req: CharacterCreateRequest,
    current_user: AuthUser = Depends(get_current_user),
):
    plan = await _get_user_plan(current_user.user_id)
    if plan != "pro":
        raise HTTPException(
            status_code=403,
            detail="Character library is available on the Pro plan only.",
        )
    row = await _library_insert(
        current_user.user_id,
        {
            "name": req.name.strip(),
            "static_features": req.static_features.strip(),
            "portrait_url": req.portrait_url.strip(),
        },
    )
    return row


@app.get("/api/characters")
async def list_characters(current_user: AuthUser = Depends(get_current_user)):
    plan = await _get_user_plan(current_user.user_id)
    if plan != "pro":
        # Hide the feature entirely for Free/Creator — empty list, not an error.
        return {"characters": []}
    chars = await _library_list(current_user.user_id)
    return {"characters": chars}


@app.delete("/api/characters/{character_id}")
async def delete_character(
    character_id: str,
    current_user: AuthUser = Depends(get_current_user),
):
    plan = await _get_user_plan(current_user.user_id)
    if plan != "pro":
        raise HTTPException(
            status_code=403,
            detail="Character library is available on the Pro plan only.",
        )
    ok = await _library_delete(current_user.user_id, character_id)
    if not ok:
        raise HTTPException(status_code=404, detail="Character not found")
    return {"ok": True}


# ── Auth helper ───────────────────────────────────────────────────────────────

@app.get("/api/me")
async def me(current_user: AuthUser = Depends(get_current_user)):
    return {
        "user_id": current_user.user_id,
        "email": current_user.email,
        "role": current_user.role,
        "is_admin": current_user.is_admin,
    }


# ── Admin endpoints ───────────────────────────────────────────────────────────

@app.get("/api/admin/stats")
async def admin_stats(_admin: AuthUser = Depends(get_current_admin)):
    jobs = list(job_store._jobs.values())
    total = len(jobs)
    return {
        "total": total,
        "completed": sum(1 for j in jobs if j.status == JobStatus.COMPLETED),
        "failed": sum(1 for j in jobs if j.status == JobStatus.FAILED),
        "running": sum(1 for j in jobs if j.status == JobStatus.RUNNING),
        "queued": sum(1 for j in jobs if j.status == JobStatus.QUEUED),
        "cancelled": sum(1 for j in jobs if j.status == JobStatus.CANCELLED),
    }


@app.get("/api/admin/jobs")
async def admin_list_jobs(
    limit: int = 50,
    offset: int = 0,
    _admin: AuthUser = Depends(get_current_admin),
):
    jobs = sorted(job_store._jobs.values(), key=lambda j: j.created_at, reverse=True)
    page = jobs[offset: offset + limit]
    return {
        "total": len(jobs),
        "jobs": [j.to_dict(include_events=False) for j in page],
    }


@app.get("/api/admin/jobs/{job_id}")
async def admin_get_job(job_id: str, _admin: AuthUser = Depends(get_current_admin)):
    job = job_store.get(job_id)
    if job:
        return job.to_dict(include_events=True)
    data = await job_store.get_or_fetch_dict(job_id)
    if not data:
        raise HTTPException(status_code=404, detail="Job not found")
    return data


@app.post("/api/admin/jobs/{job_id}/retry")
async def admin_retry_job(
    job_id: str,
    background_tasks: BackgroundTasks,
    _admin: AuthUser = Depends(get_current_admin),
):
    old = job_store.get(job_id)
    if not old:
        raise HTTPException(status_code=404, detail="Job not found")
    if old.status == JobStatus.RUNNING:
        raise HTTPException(status_code=400, detail="Job is still running")

    new_job = await job_store.create(
        idea=old.idea,
        style=old.style,
        director_style=old.director_style,
        aspect_ratio=old.aspect_ratio,
        num_scenes=old.num_scenes,
        user_requirement=old.user_requirement,
        demo=old.demo,
        user_id=old.user_id,
        user_email=old.user_email,
        music_enabled=old.music_enabled,
        dialogue_enabled=old.dialogue_enabled,
        plan=old.plan,
    )
    api_key = os.environ.get("MUAPI_KEY", "")
    background_tasks.add_task(run_generation_job, new_job, api_key)
    return {"new_job_id": new_job.id}


@app.delete("/api/admin/jobs/{job_id}")
async def admin_delete_job(job_id: str, _admin: AuthUser = Depends(get_current_admin)):
    job = job_store.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    if job.status == JobStatus.RUNNING:
        job.status = JobStatus.CANCELLED
    await job_store.delete(job_id)
    return {"deleted": job_id}


# ── Credits endpoints ─────────────────────────────────────────────────────────

@app.get("/api/credits")
async def get_credits(current_user: AuthUser = Depends(get_current_user)):
    """Return current credit balance and recent ledger entries."""
    credits = await _get_user_credits(current_user.user_id)
    ledger = []
    if SUPABASE_URL and SUPABASE_SERVICE_KEY:
        try:
            async with httpx.AsyncClient(timeout=6.0) as client:
                resp = await client.get(
                    f"{SUPABASE_URL}/rest/v1/credit_ledger",
                    params={
                        "user_id": f"eq.{current_user.user_id}",
                        "select": "amount,reason,job_id,created_at",
                        "order": "created_at.desc",
                        "limit": "20",
                    },
                    headers={"apikey": SUPABASE_SERVICE_KEY, "Authorization": f"Bearer {SUPABASE_SERVICE_KEY}"},
                )
                ledger = resp.json() if isinstance(resp.json(), list) else []
        except Exception:
            pass
    return {"credits": credits, "ledger": ledger}


# ── Stripe endpoints ──────────────────────────────────────────────────────────

class CheckoutRequest(BaseModel):
    plan: str
    success_url: str
    cancel_url: str


class PortalRequest(BaseModel):
    return_url: str


@app.post("/api/create-checkout-session")
async def create_checkout_session(
    req: CheckoutRequest,
    current_user: AuthUser = Depends(get_current_user),
):
    from stripe_integration import create_checkout_session as _create, get_price_id

    price_id = get_price_id(req.plan)
    if not price_id:
        raise HTTPException(
            status_code=400,
            detail=f"No Stripe price configured for plan '{req.plan}'.",
        )
    try:
        url = await _create(
            price_id=price_id,
            user_id=current_user.user_id,
            user_email=current_user.email,
            success_url=req.success_url,
            cancel_url=req.cancel_url,
        )
        return {"url": url}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


class BuyCreditsRequest(BaseModel):
    package: str  # SMALL | MEDIUM | LARGE
    success_url: str
    cancel_url: str


@app.post("/api/buy-credits")
async def buy_credits(
    req: BuyCreditsRequest,
    current_user: AuthUser = Depends(get_current_user),
):
    """Create a one-time Stripe Checkout session for a credit package."""
    from stripe_integration import create_checkout_session as _create, get_credit_price_id, CREDIT_PACKAGES

    pkg_key = req.package.upper()
    if pkg_key not in CREDIT_PACKAGES:
        raise HTTPException(status_code=400, detail=f"Unknown credit package: {req.package}")

    price_id = get_credit_price_id(pkg_key)
    if not price_id:
        raise HTTPException(
            status_code=400,
            detail=f"No Stripe price configured for credit package '{req.package}'. Set STRIPE_PRICE_CREDITS_{pkg_key} env var.",
        )
    try:
        url = await _create(
            price_id=price_id,
            user_id=current_user.user_id,
            user_email=current_user.email,
            success_url=req.success_url,
            cancel_url=req.cancel_url,
            mode="payment",
            metadata={"credit_package": pkg_key},
        )
        return {"url": url, "package": pkg_key, "credits": CREDIT_PACKAGES[pkg_key]["credits"]}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@app.post("/api/stripe-portal")
async def stripe_portal(
    req: PortalRequest,
    current_user: AuthUser = Depends(get_current_user),
):
    """Create a Stripe Billing Portal session for the authenticated user."""
    from stripe_integration import create_portal_session

    customer_id: Optional[str] = None
    if SUPABASE_URL and SUPABASE_SERVICE_KEY:
        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.get(
                    f"{SUPABASE_URL}/rest/v1/profiles",
                    params={
                        "id": f"eq.{current_user.user_id}",
                        "select": "stripe_customer_id",
                        "limit": "1",
                    },
                    headers={
                        "apikey": SUPABASE_SERVICE_KEY,
                        "Authorization": f"Bearer {SUPABASE_SERVICE_KEY}",
                    },
                )
                data = resp.json()
                if isinstance(data, list) and data:
                    customer_id = data[0].get("stripe_customer_id")
        except Exception:
            pass

    if not customer_id:
        raise HTTPException(
            status_code=400,
            detail="Bu hesap için Stripe müşteri kaydı bulunamadı. Önce bir abonelik başlatın.",
        )

    try:
        url = await create_portal_session(
            customer_id=customer_id,
            return_url=req.return_url,
        )
        return {"url": url}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@app.post("/api/stripe-webhook")
async def stripe_webhook(request: Request):
    from stripe_integration import handle_webhook

    payload = await request.body()
    sig = request.headers.get("stripe-signature", "")
    try:
        result = await handle_webhook(payload, sig)
        return result
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("api:app", host="0.0.0.0", port=8000, reload=True)
