"""robots.txt has no inheritance, and that is how a private route gets opened.

A `User-agent:` group REPLACES the `*` group for the bot it names rather than
adding to it. So the obvious, well-meant way to say "yes, AI crawlers are
welcome here" --

    User-agent: GPTBot
    Allow: /

-- does not restate the default. It discards every Disallow in the `*` group
for that one crawler, and /admin, /dashboard, /generate, /auth, /api and /login
become crawlable by it. Nothing in the file looks wrong afterwards: the `*`
group above is still correct, and the new group is two lines that plainly say
what was intended.

client/app/robots.js therefore builds every named group from the same
`disallow` list as `*`. This test reads that file and pins the construction,
because the failure it prevents is invisible in review and is not the kind of
thing anybody re-derives while adding the fifteenth crawler to a list.

It asserts on the SOURCE rather than on a generated robots.txt so it runs in a
checkout without a Next build. That is a weaker check -- it verifies how the
groups are built, not what came out -- so it also pins the two things that
would make a correct-looking construction produce nothing: an empty crawler
list, and an empty private-path list.
"""

import os
import re

import pytest

ROBOTS = os.path.join(
    os.path.dirname(__file__), "..", "..", "client", "app", "robots.js"
)

#: The routes that must never be crawlable, by anyone. Mirrors PRIVATE_PATHS in
#: robots.js; the test below checks the file still lists exactly these, so a
#: route removed from the site's own list fails here rather than silently
#: shrinking what is protected.
EXPECTED_PRIVATE = {"/admin", "/dashboard", "/generate", "/auth", "/api", "/login"}


@pytest.fixture(scope="module")
def source():
    with open(ROBOTS, encoding="utf-8") as f:
        return f.read()


def _private_paths(source):
    block = re.search(r"const PRIVATE_PATHS = \[(.*?)\];", source, re.S).group(1)
    return set(re.findall(r'"([^"]+)"', block))


def _ai_crawlers(source):
    block = re.search(r"const AI_CRAWLERS = \[(.*?)\];", source, re.S).group(1)
    return [ua for ua in re.findall(r'"([^"]+)"', block)]


def test_the_private_routes_are_still_the_ones_we_think_they_are(source):
    assert _private_paths(source) == EXPECTED_PRIVATE


def test_every_named_crawler_group_carries_the_same_disallows_as_the_default(source):
    """The one assertion this file exists for."""
    rules = re.search(r"rules: \[(.*?)\n    \],", source, re.S).group(1)

    # The default group, and then the named ones -- generated by mapping the
    # crawler list over the SAME `disallow` binding the default group uses.
    assert '{ userAgent: "*", allow: "/", disallow }' in rules
    assert (
        'AI_CRAWLERS.map((userAgent) => ({ userAgent, allow: "/", disallow }))' in rules
    ), "named groups must reuse the default group's disallow list, not restate it"

    # No group may carry a disallow list written out by hand: that is the copy
    # that goes stale when a private route is added.
    assert "disallow: [" not in rules, "a hand-written disallow list has appeared"


def test_the_crawler_list_is_not_empty_and_has_no_duplicates(source):
    """A correct construction over an empty list emits no groups at all, and
    the test above would still pass."""
    crawlers = _ai_crawlers(source)
    assert len(crawlers) >= 5, crawlers
    assert len(crawlers) == len(set(crawlers)), "the same crawler is listed twice"


def test_google_extended_is_named_because_googlebot_does_not_cover_it(source):
    """Googlebot's permissions do not govern Gemini or AI Overviews; that is a
    separate token, and it is the one this site most wants to be read by."""
    assert "Google-Extended" in _ai_crawlers(source)
